name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0   # (Spotify linklerini açmak için şimdiden ekledim)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png
  # adaptive_icon_monochrome: assets/icon/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
